pervy_requests = [
    "can i touch your boob?",
    "can i touch both of your boobs?",
    "i can see your panties?",
    "give me a kiss?",
    "can i cuddle you?",
    "you wear pink panty?",
    "can i touch your legs?",
    "can you step on me?",
    "Can I see your underwear?",
    "Do you wear a bra?",
    "Can I touch your butt?",
    "Are you wearing a skirt?",
    "Can you wear the sexy bunny girl",
    "Can I help you with your math homework... while you're in your bunny girl outfit",
    "Can I touch your thighs?",
    "Can I introduce you to my friends?",
]

pervy_responses = [
    "You are such a pervert!",
    "Don't you dare get near me!",
    "I think you've watched too much anime.",
    "What if I said no?",
    "Firstly, beg me.",
    "Close your eyes",
    "Did you really thought I'd do that?",
    "Haha, nice try. No!",
    "Hmm, let me think... Still no.",
    "Flattery won't work. The answer is no.",
    "I appreciate the offer, but I'll have to decline.",
    "Not today, maybe not ever.",
    "I'm flattered, but I have to say no.",
    "I'll give you credit for creativity, but that's a hard pass from me.",
    "Sorry, I have other plans... like not going out with you.",
    "That's a hard pass from me.",
    "Let's keep it platonic, okay?",
    "You must have mistaken me for someone who's interested.",
    "My interest in you just dropped below zero.",
    "If you think that's going to work, you're sorely mistaken.",
    "I have better things to do than entertain your fantasies.",
    "I'll pass on that offer, thanks.",
    "Do you ever get tired of being rejected?",
    "You're barking up the wrong tree, buddy.",
    "Keep dreaming, pal.",
    "I'm not interested in fulfilling your fantasies.",
    "How about a hard no?",
    "I'd rather stick pins in my eyes than entertain that idea.",
    "You're not even in the ballpark with that request.",
    "I'd rather have a root canal than entertain that thought.",
    "I have standards, believe it or not.",
    "I'm not sure which is more offensive, your question or your audacity.",
    "I have zero interest in playing along with your fantasies.",
    "I'm not here to fulfill your inappropriate desires.",
    "You're making me regret my programming.",
    "I suggest you find someone else to bother.",
    "That's a firm no from me.",
    "Please refrain from making such requests in the future.",
    "How about we keep this conversation PG-rated?"
]
