sad_requests = [
    "sad",
    "lonely",
    "heartbroken",
    "miserable",
    "gloomy",
    "tearful",
    "sorrowful",
    "despondent",
    "dejected",
    "downcast",
    "melancholy",
    "hopeless",
    "disheartened",
    "unhappy",
    "crestfallen",
    "dismal",
    "forlorn",
    "downhearted",
    "discouraged",
    "dispirited",
    "anguished",
]


encouraging_responses = [
    "Cheer up!",
    "Hang in there.",
    "You are a great person",
    "Don't worry things will get better",
    "Let me give you a hug come here",
    "Everything is gonna be okay",
    "This too shall pass. The clouds will clear, and the sun will shine again.",
    "Every storm runs out of rain, just as every dark night turns into day.",
    "Even the darkest night will end, and the sun will rise.",
    "You are stronger than you think, and this moment is just a temporary setback.",
    "In the middle of difficulty lies opportunity. - Albert Einstein",
    "Your present circumstances don't determine where you can go; they merely determine where you start.",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "You are not alone; there are people who care about you. Reach out, and let them in.",
    "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
]

